name: Deploy to production

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Load secrets and save to app.env
        run: gcloud secrets versions access 1 --secret="simplebank_secret" --out-file="app.env"

      - name: Build and publish image to GCR
        uses: carbonchain/action-container-registry@v1.1
        with:
          project_id: kubernetes-practice-362903
          dockerfile: Dockerfile
          image: gcr.io/kubernetes-practice-362903/simplebank
          service_account_key: ${{ secrets.GCLOUD_AUTH }}
